---
spring:
  main:
    banner-mode: off
  application:
    name: "harmny-user-service"
  data:
    mongodb:
      authentication-database: ${SPRING_DATA_MONGODB_AUTH_DB:harmny}
      username: ${SPRING_DATA_MONGODB_USERNAME:harmny}
      password: ${SPRING_DATA_MONGODB_PASSWORD:harmny}
      database: ${SPRING_DATA_MONGODB_DATABASE:harmny}
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}

server:
  port: 8081

harmny:
  jwt-key: ${HARMNY_JWT_TOKEN:DAVLtjoTHQ3uhsGm2VstWj5M2JsdhhxQPy71BL11XQ4E5OpRgfCYjNPELkP1M6g}
