---
spring:
  main:
    banner-mode: off
  application:
    name: "harmny-user-service"
  data:
    mongodb:
      authentication-database: "harmny"
      username: "harmny"
      password: "harmny"
      database: "harmny"
      host: "localhost"
      port: "27017"

server:
  port: 8081

jwt:
  key: ${JWT_TOKEN:DAVLtjoTHQ3uhsGm2VstWj5M2JsdhhxQPy71BL11XQ4E5OpRgfCYjNPELkP1M6g}
